/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_781279_49[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 4.951012750478343, 2.7897326490923775, 1.9176286288838142 };
const float ei_classifier_anom_mean[3] = { 4.714792071859411, 2.488218415093879, 2.0041970496538957 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { 1.2876250743865967, -0.201784148812294, -0.38368529081344604 }, 0.44208362529828193 },
	{ ( float[3] ) { -0.9497427344322205, -0.8849113583564758, -1.0300596952438354 }, 0.2013881759912542 },
	{ ( float[3] ) { -0.7396517395973206, -0.45940834283828735, 1.332540512084961 }, 0.2546910217357828 },
	{ ( float[3] ) { 1.0862394571304321, -0.3149372935295105, -0.14626604318618774 }, 0.3938941371954247 },
	{ ( float[3] ) { -0.5478730797767639, 0.05840782821178436, 1.4697859287261963 }, 0.44520448936806695 },
	{ ( float[3] ) { -0.730626106262207, -0.3131355941295624, -0.7616052627563477 }, 0.28554892824309563 },
	{ ( float[3] ) { -0.3502921164035797, 3.411665678024292, -0.33027011156082153 }, 0.5177667268410996 },
	{ ( float[3] ) { 1.7109301090240479, 0.2824917733669281, 0.42511019110679626 }, 0.4634764515507905 },
	{ ( float[3] ) { 1.126882791519165, 0.22324106097221375, -0.13529784977436066 }, 0.4597802962840517 },
	{ ( float[3] ) { -0.4992675483226776, -0.33456146717071533, 2.351458787918091 }, 0.6966852347134489 },
	{ ( float[3] ) { -0.6573604941368103, -0.0901542454957962, -0.761150598526001 }, 0.2509250838201196 },
	{ ( float[3] ) { -0.6505458354949951, 0.0005134753882884979, 1.8591339588165283 }, 0.3874257619637051 },
	{ ( float[3] ) { -0.6404937505722046, -0.2575635612010956, 1.674996256828308 }, 0.44118221184006495 },
	{ ( float[3] ) { 0.9717732667922974, 3.3336799144744873, 1.1941790580749512 }, 0.2867727837118793 },
	{ ( float[3] ) { -0.2987474203109741, 1.68306303024292, 0.08796830475330353 }, 0.4802017419668724 },
	{ ( float[3] ) { 1.307753324508667, 0.17771826684474945, -0.38903889060020447 }, 0.3184351165796092 },
	{ ( float[3] ) { 1.254988431930542, -0.4019601345062256, 0.5411701798439026 }, 0.4447193154254579 },
	{ ( float[3] ) { -0.040093544870615005, 3.7587153911590576, -0.13978774845600128 }, 0.6897169542973925 },
	{ ( float[3] ) { 1.5725219249725342, 0.7196007966995239, 0.527588427066803 }, 0.42104447284563246 },
	{ ( float[3] ) { -0.3995652496814728, -0.10946235060691833, 2.8175556659698486 }, 0.6838489945175961 },
	{ ( float[3] ) { 0.8756040930747986, -0.12487513571977615, 0.6466326713562012 }, 0.4893914016894772 },
	{ ( float[3] ) { -0.7074158787727356, -0.24593324959278107, -0.4675731360912323 }, 0.19033541768831103 },
	{ ( float[3] ) { -0.19707797467708588, 0.9617511034011841, 2.318636178970337 }, 0.789599221937823 },
	{ ( float[3] ) { 0.8893953561782837, -0.10691526532173157, -0.39105117321014404 }, 0.30970139372829414 },
	{ ( float[3] ) { 1.433549165725708, 0.6112751364707947, 0.007444632705301046 }, 0.40372875895166965 },
	{ ( float[3] ) { 1.8550012111663818, 0.03571205586194992, 0.8535289168357849 }, 0.6668462550670938 },
	{ ( float[3] ) { 1.8786753416061401, 0.14698973298072815, 1.4110908508300781 }, 0.2978867188430744 },
	{ ( float[3] ) { 0.7619092464447021, 2.806682586669922, 0.7540162205696106 }, 0.4340073416364735 },
	{ ( float[3] ) { -0.45367273688316345, 0.6112172603607178, 0.1321888118982315 }, 0.30751134715608025 },
	{ ( float[3] ) { -0.33632272481918335, 0.9439042210578918, 0.3597339689731598 }, 0.48456312285617464 },
	{ ( float[3] ) { -0.5266637802124023, 0.3272242248058319, -0.15080411732196808 }, 0.19827238648679807 },
	{ ( float[3] ) { -0.776119589805603, -0.5470508337020874, 0.9614677429199219 }, 0.40540316827344797 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
